#!/usr/bin/env bash

cd /gpfs/group/pipkin/jycATAC/MACS2/pileup_bdg/srt_bdg

file_arr=(Bcl6KO_Th1_rep1 Bcl6KO_Th1_rep2 Bcl6KO_Th1_rep3 DKO_Tfh_rep1 DKO_Tfh_rep2 DKO_Tfh_rep3 DKO_Th1_rep1 DKO_Th1_rep2 DKO_Th1_rep3 Naive_rep1 Naive_rep2 Naive_rep3 Prdm1KO_Tfh_rep1 Prdm1KO_Tfh_rep2 Prdm1KO_Tfh_rep3 WT_Tfh_rep1 WT_Tfh_rep2 WT_Tfh_rep3 WT_Th1_rep1 WT_Th1_rep2 WT_Th1_rep3)


### Calculate file length
file_len=()

for filex in ${file_arr[@]}
do
file_len+=($(awk '{sum+=(($3-$2)*$4)} END {print sum}' ${filex}_treat_pileup_srt.bdg))
echo ${file_len[@]}
done

touch jyc_bdg_file_len.txt
echo ${file_len[@]} > jyc_bdg_file_len.txt

### Calculate scaling factor
sc_arr=()

for lenx in ${file_len[@]}
do
sc_arr+=(200000000/lenx)
done






