#!/bin/bash
#PBS -l mem=6gb
#PBS -t 0-5

### Motif score calculation: matrix score **0.86
### Combined with Homer Known motifs

wk_dir=/gpfs/home/hdiao/jycATAC/byGroup_bed
preparsed_dir=/gpfs/home/hdiao/resources
mm10_genome=/gpfs/group/databases/Mus_musculus/UCSC/mm10/Sequence/Bowtie2Index/genome.fa

cd $wk_dir

export PATH="/gpfs/home/hdiao/homer/bin:$PATH"

g_names=(Group_I Group_II Group_III Group_IV TFH_Associated TH1_Associated)
sp_names=(DKO_Tfh_vs_Prdm1KO_Tfh.dn DKO_Tfh_vs_Prdm1KO_Tfh.up DKO_Tfh_vs_WT_Tfh.dn DKO_Tfh_vs_WT_Tfh.up DKO_Th1_vs_Bcl6KO_Th1.dn DKO_Th1_vs_Bcl6KO_Th1.up DKO_Th1_vs_WT_Th1.dn DKO_Th1_vs_WT_Th1.up WT_Tfh_vs_WT_Th1.dn WT_Tfh_vs_WT_Th1.up)

for i in ${sp_names[@]}
do
	bed_name=${g_names[$PBS_ARRAYID]}__all.df.numx.c5-${i}.bed
	out_name=${g_names[$PBS_ARRAYID]}__all.df.numx.c5-${i}_mtfs
	findMotifsGenome.pl $bed_name $mm10_genome $out_name -size given -mask -preparsedDir $preparsed_dir
done
